#!/data/data/com.termux/files/usr/bin/bash

cd $HOME

# Install required tools
pkg update
pkg upgrade -y
pkg install git gnupg coreutils termux-api -y

# configure gpg key
mkdir -p $PREFIX/etc/apt/sources.list.d
cat > $PREFIX/etc/apt/sources.list.d/termux-adb.list << EOF
deb https://nohajc.github.io termux extras
EOF

# Download gpg key
wget -qO $PREFIX/etc/apt/trusted.gpg.d/nohajc.gpg https://github.com/xiv3r/adb-fastboot-termux/raw/refs/heads/main/nohajc.gpg

# update repo
pkg update
pkg install android-tools termux-adb -y

# symlinks adb and fastboot 
ln -sf $PREFIX/bin/termux-fastboot $PREFIX/bin/fastboot
ln -sf $PREFIX/bin/termux-adb $PREFIX/bin/adb

