#!/data/data/com.termux/files/usr/bin/bash

pkg update
pkg upgrade -y
pkg install gnupg coreutils termux-api -y

# configure nohajc.gpg key
mkdir -p $PREFIX/etc/apt/sources.list.d
cat > $PREFIX/etc/apt/sources.list.d/termux-adb.list << EOF
deb https://nohajc.github.io termux extras
EOF

# Download nohajc.gpg key
wget -O $PREFIX/etc/apt/trusted.gpg.d/nohajc.gpg

# update repo
pkg update
pkg install android-tools termux-adb -y

# symlinks adb and fastboot 
ln -sf $PREFIX/bin/termux-fastboot $PREFIX/bin/fastboot
ln -sf $PREFIX/bin/termux-adb $PREFIX/bin/adb
