#!/data/data/com.termux/files/usr/bin/bash

apt update
apt upgrade -y
apt install wget gnupg coreutils -y
### configure nohajc.gpg
mkdir -p $PREFIX/etc/apt/sources.list.d
cat > $PREFIX/etc/apt/sources.list.d/termux-adb.list << EOF
deb https://nohajc.github.io termux extras
EOF
###
wget -O $PREFIX/etc/apt/trusted.gpg.d/nohajc.gpg https://nohajc.github.io/nohajc.gpg
### update new repo
apt update
apt install termux-adb
### symlinks
ln -sf $PREFIX/bin/termux-fastboot $PREFIX/bin/fastboot && ln -sf $PREFIX/bin/termux-adb $PREFIX/bin/adb
###
echo "successfully installed"
